services:
  frontend:
    build: ./Frontend
    container_name: photovault-frontend
    ports:
      - "3000:3000"
    volumes:
      - ./Frontend:/app
    environment:
      - NEXT_PUBLIC_API_URL=http://localhost:8080
      - NEXT_PUBLIC_APP_ENV=dev
    depends_on:
      - backend


  backend:
    build: ./Backend
    container_name: photovault-backend
    ports:
      - "8080:8080"
    volumes:
      - ./Backend:/app
    env_file:
      - ./Backend/.env

  # db:
  #   image: postgres:15
  #   container_name: photovault-db
  #   ports:
  #     - "5432:5432"
  #   environment:
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #     POSTGRES_DB: timecapsule
  #   volumes:
  #     - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
